# -*- coding:utf-8 -*-

from app.models import db
from app.services.framework.role_service import RoleService
from app.services.framework.privilege_service import PrivilegeService
from app.services.framework.staff_sync import StaffSync

#db.drop_all(bind=['main'])
db.create_all(bind=['main'])

'''
roleService = RoleService()
privilegeService = PrivilegeService()

roleService.add_role('admin',u'管理员')
roleService.add_role('user',u'默认用户')
roleService.add_role('pe','PE')
roleService.add_role('sa','SA')

privilegeService.add_privilege('admin_user', u'用户管理')
privilegeService.add_privilege('task_config', u'任务配置')
privilegeService.add_privilege('module', u'模块管理')
privilegeService.add_privilege('resource', u'资源管理')
privilegeService.add_privilege('tag', u'标签管理')
privilegeService.add_privilege('aliyun_ecs',u'阿里云ECS')
privilegeService.add_privilege('aliyun_rds',u'阿里云RDS')
privilegeService.add_privilege('aliyun_slb',u'阿里云SLB')
privilegeService.add_privilege('aliyun_sg',u'阿里云安全组')
privilegeService.add_privilege('aliyun_dns',u'阿里云DNS')
privilegeService.add_privilege('aliyun_oss',u'阿里云OSS')
privilegeService.add_privilege('aliyun_ons',u'阿里云ONS')
privilegeService.add_privilege('aliyun_bill',u'阿里云账单')
privilegeService.add_privilege('dns',u'自建DNS')
privilegeService.add_privilege('app',u'应用')
privilegeService.add_privilege('app_protect',u'应用保护')
privilegeService.add_privilege('svn','SVN')
privilegeService.add_privilege('git','Git')
privilegeService.add_privilege('docker','Docker')

privilegeService.link_role_privilege(1, 1, True, True)
privilegeService.link_role_privilege(1, 2, True, True)
privilegeService.link_role_privilege(1, 3, True, True)
privilegeService.link_role_privilege(1, 4, True, True)
privilegeService.link_role_privilege(1, 5, True, True)
privilegeService.link_role_privilege(1, 6, True, True)
privilegeService.link_role_privilege(1, 7, True, True)
privilegeService.link_role_privilege(1, 8, True, True)
privilegeService.link_role_privilege(1, 9, True, True)
privilegeService.link_role_privilege(1, 10, True, True)
privilegeService.link_role_privilege(1, 11, True, True)
privilegeService.link_role_privilege(1, 12, True, True)
privilegeService.link_role_privilege(1, 13, True, True)
privilegeService.link_role_privilege(1, 14, True, True)
privilegeService.link_role_privilege(1, 15, True, True)
privilegeService.link_role_privilege(1, 16, True, True)
privilegeService.link_role_privilege(1, 17, True, True)
privilegeService.link_role_privilege(1, 18, True, True)
privilegeService.link_role_privilege(1, 19, True, True)

privilegeService.link_role_privilege(2, 6, True, False)
privilegeService.link_role_privilege(2, 7, True, False)
privilegeService.link_role_privilege(2, 8, True, False)
privilegeService.link_role_privilege(2, 9, True, False)
privilegeService.link_role_privilege(2, 10, True, False)
privilegeService.link_role_privilege(2, 11, True, False)
privilegeService.link_role_privilege(2, 12, True, False)
privilegeService.link_role_privilege(2, 13, True, False)
privilegeService.link_role_privilege(2, 14, True, False)
privilegeService.link_role_privilege(2, 15, True, False)

privilegeService.link_role_privilege(3, 6, True, True)
privilegeService.link_role_privilege(3, 7, True, True)
privilegeService.link_role_privilege(3, 8, True, True)
privilegeService.link_role_privilege(3, 9, True, True)
privilegeService.link_role_privilege(3, 10, True, True)
privilegeService.link_role_privilege(3, 11, True, True)
privilegeService.link_role_privilege(3, 12, True, True)
privilegeService.link_role_privilege(3, 13, True, True)
privilegeService.link_role_privilege(3, 14, True, True)
privilegeService.link_role_privilege(3, 15, True, True)
privilegeService.link_role_privilege(3, 16, True, True)
privilegeService.link_role_privilege(3, 17, True, True)
privilegeService.link_role_privilege(3, 18, True, True)
privilegeService.link_role_privilege(3, 19, True, True)

privilegeService.link_role_privilege(4, 6, True, True)
privilegeService.link_role_privilege(4, 7, True, True)
privilegeService.link_role_privilege(4, 8, True, True)
privilegeService.link_role_privilege(4, 9, True, True)
privilegeService.link_role_privilege(4, 10, True, True)
privilegeService.link_role_privilege(4, 11, True, True)
privilegeService.link_role_privilege(4, 12, True, True)
privilegeService.link_role_privilege(4, 13, True, True)
privilegeService.link_role_privilege(4, 14, True, True)
privilegeService.link_role_privilege(4, 15, True, True)

StaffSync.sync_department()

roleService.link_user_role('wz000850', 1)
'''